### ISSUE TITLE
Load co-motion events into Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#104]
Please load all events from the co-motion.ca website with artifact `co-motion-ca`.

My initial analysis is that this website will work with the Artsdata Pipeline Action.
- headless (JSON-LD is injected into the page via javascript)
- paginated https://co-motion.ca/spectacles/?page=2

Note: this same website is being transitioned from the currently active and running Footlight Console http://kg.artsdata.ca/culture-creates/footlight/co-motion-ca to Orion.  Once successful I will remove it from Footlight Console.

**Comment by dev-aravind** [comment]
@saumier You can test this [here](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20co-motion-ca&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-orion/co-motion-ca).

**Comment by saumier** [comment]
@dev-aravind This looks pretty good. However there is something off with the startDates. When I check on actual webpage the date is one day off.  

Examples:
[Foie gras in Artsdata](https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fco-motion.ca%2Ftemporary%2F067b9b25-ab19-4d95-a41b-a8d5fc9d6ff5) starts 2026-02-22T20:00:00-05:00

But on the website the event Foie gras starts 2026-02-21

Also Ménopause[https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fco-motion.ca%2Ftemporary%2F8ad51510-bd3e-4a85-b142-8efab164a551] is one day off.

If the first 2 events I checked are off, then I assume there are many with the wrong startDate.

**Comment by dev-aravind** [comment]
@saumier This is an issue with their JSON-LD (see attached screenshots)

[Menopause](https://co-motion.ca/spectacles/menopause/) - date is 2026-03-08 in JSON-LD, which is one day off
![Image](https://github.com/user-attachments/assets/2261d3e0-ae6e-4cc0-9130-67c18d5ae5c8)

[Foie gras](https://co-motion.ca/spectacles/mariana-mazza-foie-gras/) - date is 2026-02-22 in JSON-LD, which is one day off
![Image](https://github.com/user-attachments/assets/b228d535-2e28-4322-8585-8c3d24f8289f)


You can go to the event page in their website and inspect, search startDate to reach the above screengrabs

**Comment by saumier** [comment]
@dev-aravind This is a really unusual bug.

This is what I wrote to our client Maude at SignéLaval:

> There is a  ’show stopper’ with the data. The data in not yet acceptable because the event startDates are 1 day off when crawled by Artsdata. Co-motion’s script for their JSON-LD is being affected by the time zone of crawler. The Artsdata crawler is in a different timezone and co-motion's script is changing the dates by 1 day.  This is the first time I have seen this behaviour.

> Culture Creates is working on fixing this problem for co-motion at our end. But this will only happen after the holidays in January.

> I also recommend Co-motion fix this problem in their script. It may affect other crawlers like Google or 3rd party crawlers that read their JSON-LD. The JSON-LD added by co-motion’s script should not depend on the time of day or timezone of the browser viewing the event. However I understand that this is a very technical fix and I would like to explain in more detail the way to reproduce and test this issue for co-motion before asking co-motion to fix it.  I can write a detailed explanation in January. 

Lets do the following:
- [ ]  Please write down very precise reproduction steps to view the problem by changing the date locally. I tried setting my clock to Sydney, Australia on Friday but I did not succeed in reproducing the problem.  It might depend on the time of day so please note down the time of day that you are able to reproduce the bug.  I will send there repro steps to the developers at co-motion in January. 
- [ ] Try to fix the problem by setting the browser/OS of the virtual machine running the Chrome headless browser to ET or UTC or something known. You may need to experiment here.

**Comment by dev-aravind** [comment]
@saumier The docker image now runs in America/Toronto timezone and the issue was fixed. See [Ménopause](https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fco-motion.ca%2Ftemporary%2Fb09750d8-ab18-4706-9d1a-c8edc88fb2b1) and [Foie gras](https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fco-motion.ca%2Ftemporary%2Fd5f8b127-5d36-4548-bfb2-cb348e074f60) for reference.

Reproduction steps:

Set the timezone of your local machine to UTC
Go to [this](https://co-motion.ca/spectacles/menopause/) URL for the event Ménopause
Inspect element and check the start date in the JSON-LD embedded in the HTML (search startDate)
You can see that the start date is off by one day (2026-03-08T20:00:00-05:00 instead of 2026-03-07T20:00:00-05:00)

I was able to reproduce this during my working hours consistently. The time of the day when this comment is published would be a good time to reproduce the bug. Let me know if you need any more support.

**Comment by saumier** [comment]
@dev-aravind Great. Thanks for the repro steps.
