### ISSUE TITLE
Port ScenePro API Huginn to OntoRefine

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#12]
This project should have its own repo called "artsdata-planet-scenepro" because we collaborate with this organization. Please create the repo when you start working on this.

This is an API with Organizations and Places, so we should use the same approach as Suhail in the Culture Mauricie project with OntoRefine. 

The API doc is here https://api-docs.scenepro.ca

Credentials for GET
[/organizations/diffuser/](https://api-docs.scenepro.ca/#/Organization/get_organizations_diffuser__offset___limit_)
```
 "url": [
    "https://public-api.scenepro.ca/capacoa/organizations/diffuser/0/200?networkId=2"
  ],
  "headers": {
    "Ocp-Apim-Subscription-Key": "44c4455927594abfb8127ec918b93c73;product=capacoa"
  }
```

For the RDF mapping from JSON, please look at the actual data in Artsdata exported using Huginn.
https://artsdata-nebula-d1ec887e2637.herokuapp.com/query/show?title=Organization%20entities%20in%20scenepro-orgs%20%288379%20triples%29&sparql=list_organizations&graph=http://kg.artsdata.ca/culture-creates/huginn/scenepro-orgs

The Organization entity URIs should take the form http://scenepro.ca#Organization[id]

And Places (venues) http://scenepro.ca#Venue[id]

This is the Huginn setup https://huginn-staging.herokuapp.com/scenarios/21/diagram but let me know if you need access, I can't remember how much of Huginn you can view.

**Comment by saumier** [comment]
@dev-aravind Please use artifact name `scenepro-orgs`

**Comment by saumier** [comment]
@dev-aravind Here are some points to fix in the ScenePro RDF:

Comparing 
huginn version: [Théâtre Lac-Brome](https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fscenepro.ca%23Organization1293)
artsdata-planet-scenepro version: [Théâtre Lac-Brome](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-scenepro%2Fscenepro-orgs)

1. Use URI template which is different form Huginn but better in the long run:
       - https://scenepro.ca/id/organization/[id] 
       - https://scenepro.ca/id/venue/[id] 
 example: https://scenepro.ca/id/organization/1293

2. Fix %20logo in organizations
3. Format the telephone number +1-438-496-5618
4. Add missing Québec Enterprise Number  (http://www.wikidata.org/prop/direct/P10503)
5. Concatenate "http://www.wikidata.org/entity/" + identifier and add to SameAS
6.  Create a SKOS concept for additionalType and assign one or more URIs (different from huginn version).

There are 4 SKOS concepts needed for ScenePro Organizations:
"VENUE_OWNER"
"DIFFUSER"
"OTHER"
"PRODUCER"

7. Use schema:Role to link Organization to one or more venues.
See example: https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fscenepro.ca%23Organization1938

Example data (turtle notation):
sp:Organization1938  schema:location  
     [ a schema:Role ; schema:roleName "gestionnaire"@fr ; schema:location sp:Venue343 ]

**Comment by dev-aravind** [comment]
@saumier I've update the cofiguration to fix the issues that you mentioned above and also found some issues which I was not able to solve.

1. Some of the entities did not have a sameAs value in the JSON data(artsdataUri, wikidataUri). But in the huggin import that we did, there were sameAs values for them. These entities are also showing a SHACL violation.
2. The descriptions in the huggin import properly shows the HTML tags in them, but in our ontorefine version the HTML tags are parsed in the viewer and they are not visible.

Let me know what you think.

**Comment by dev-aravind** [comment]
@saumier I fixed all the issues that you mentioned in the previous comment. Please review this ticket.

**Comment by saumier** [comment]
@dev-aravind 

Please add the actual location in the schema:Role entity otherwise the data doesn't say which Place the role is acting on.

Example [Usine C
](http://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fscenepro.ca%2Fid%2Forganization%2F1938) is the operator of 2 Places. 

> Use schema:Role to link Organization to one or more venues.
See example: https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fscenepro.ca%23Organization1938

> Example data (turtle notation):
sp:Organization1938 schema:location
[ a schema:Role ; schema:roleName "gestionnaire"@fr ; schema:location sp:Venue343 ]

**Comment by saumier** [comment]
Looks good. Thx.
