### ISSUE TITLE
Port Le Vivier Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#13]
Le Vivier - Events located on this web page: https://levivier.ca/fr

Old Huginn: https://huginn-staging.herokuapp.com/scenarios/24

Please name this artifact : levivier-ca

**Comment by dev-aravind** [comment]
@saumier  Same issue mentioned in this [comment](https://github.com/culturecreates/artsdata-orion/issues/14#issuecomment-1895747872)

**Comment by dev-aravind** [comment]
@saumier This data has a date issue. I'm guessing maybe because the date type is missing. Let me know what you think.



![Image](https://github.com/culturecreates/artsdata-orion/assets/132546883/83a8acd2-6e5a-4563-aa57-2777ad57898b)

**Comment by saumier** [comment]
@dev-aravind Yes. The SHACL error is because the datatype is not xsd:dateTime.  When data is loaded into Artsdata through the databus, it converts all Literals with datatype schema:Date into datatype xsd:dateTime. It also sets all schema:startDate and schema:endDate literals to xsd:dateTime incase there was no datatype in the incoming data.

Can you tell me what the datatype is from the data you scraped from the web page?

**Comment by dev-aravind** [comment]
@saumier The scraped data does not have a datatype for dateModified, it has a literal as it's value. Sample data:



![Image](https://github.com/culturecreates/artsdata-orion/assets/132546883/9d137aef-fa0f-42de-a77a-43fe73386a88)

**Comment by saumier** [comment]
@dev-aravind Actually no.  In the data on the Webpage there is a datatype of schema:Date. Here is the line:
`"http://schema.org/dateModified":[{"@type":"http://schema.org/Date","@value":"2023-09-15T10:38:22-0400"}]}`

Can you explain how the datatype is set from the @context?

**Comment by dev-aravind** [comment]
@saumier 

[This](https://github.com/culturecreates/artsdata-orion/blob/main/tests/date_test.rb) is the test file that I worked on to check if every date had a type in them after the SPARQL transformation(test_date_type)

This was my first approach but I wasn't able to get any value in date_type during my testing.

events = graph.query([nil, RDF::type, RDF::Vocab::SCHEMA.Event]).each.subjects
dates = graph.query([events.first, RDF::Vocab::SCHEMA.startDate, nil]).each.objects
date_type = graph.query([dates.first, RDF::type, nil]).each.objects

Let me know what you think.

**Comment by saumier** [comment]
@dev-aravind I added a new test that fails. Try to get it to pass!

Here is the output when it fails
```
Failure:
DateTest#test_date_type_in_context [tests/date_test.rb:41]:
Data type of startDate should be preserved after fixing.
--- expected
+++ actual
@@ -1 +1 @@
-#<RDF::URI:0xXXXXXX URI:http://schema.org/Date>
+#<RDF::URI:0xXXXXXX URI:dateTime>
```
The expected output is marked with  -
The expected output is schema:Date because that is what is assigned in the @context.
But the actual output does not match the expected output. 
The actual output is marked with +
The actual output is :dateTime which has two problems: xsd is your SPARQL is missing a prefix declaration, and it should remain as it was before the fix, which is the type schema:Date.

The goal of the SPARQL should be to ONLY fix the syntax in the date format, and not change the data type.

I used `.first` to check the resulting triple because in my test file `test_date_type_in_context.jsonld` there is only one event to check. But this can be extended to check multiple triples.

I will let you try to fix the SPARQL to make the test pass, and then we can review the SPARQL in detail because I have several other comments. Lets go step-by-step :-)

**Comment by saumier** [comment]
> [@saumier](https://github.com/saumier)
> 
> [This](https://github.com/culturecreates/artsdata-orion/blob/main/tests/date_test.rb) is the test file that I worked on to check if every date had a type in them after the SPARQL transformation(test_date_type)
> 
> The below code snippet was my first approach but I wasn't able to get any value in date_type during my testing.
> 
> events = graph.query([nil, RDF::type, RDF::Vocab::SCHEMA.Event]).each.subjects
> dates = graph.query([events.first, RDF::Vocab::SCHEMA.startDate, nil]).each.objects
> date_type = graph.query([dates.first, RDF::type, nil]).each.objects
> Let me know what you think.

The mistake in your code snippet above is querying the graph to get the data type when you already have the object. To get the data type of the first date just do date_type = dates.first.datatype

Have you tried using IRB? It is an easy way in Ruby to try out the commands.  Here is a dump of my terminal using IRB to step through your code snippet above.

```
saumier@Gregorys-MacBook-Pro artsdata-orion % irb
 :001 > require 'linkeddata'
 => true 
 :002 > fix_date_timezone_sparql_file = './sparql/fix_date_timezone.sparql'
 => "./sparql/fix_date_timezone.sparql" 
 :003 > @sparql = SPARQL.parse(File.read(fix_date_timezone_sparql_file), update: true)
 => #<SPARQL::Algebra::Operator::Prefix:0x749f0(( ((schema: <http://schema.org/>)) (update (modify (filter (exprlist (= (datatype ?old_d... 
 :004 > graph = RDF::Graph.load("./tests/fixtures/test_date_timezone_fix.jsonld")
 => #<RDF::Graph:0x7605c(default)> 
 :005 > events = graph.query([nil, RDF::type, RDF::Vocab::SCHEMA.Event]).each.subjects
 => 
[#<RDF::URI:0x78780 URI:http://example.com/event1>,
... 
 :006 > dates = graph.query([events.first, RDF::Vocab::SCHEMA.startDate, nil]).each.objects
 => [#<RDF::Literal:0x7b110("2024-02-03T20:00:00-0700"^^<http://schema.org/Date>)>] 
 :007 > data_type = dates.first.datatype
 => #<RDF::URI:0x85980 URI:http://schema.org/Date> 
```

**Comment by saumier** [comment]
@dev-aravind I creates some new tests for the SPARQL that fixes the timezone. Please check them out and run them. There is one failing. Try to get it to pass.

I also renamed the tests to match the sparql name + "_test.rb". This is a convention I would like to follow. So each sparql has a corresponding test file.

**Comment by dev-aravind** [comment]
@saumier I've updated the SPARQL to make the unit tests pass. Please check it out and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind Thanks. The tests passed. I added 2 more tests for common cases that I found in the data when there is no timezone offset (date only) and when the shortcut `Z` is used instead of an offset like `-04:30`. These startDates should be skipped. However, one of the tests is failing. Please make them pass. As we come across new cases of timezones, we should add them to the tests.

**Comment by saumier** [comment]
Looks good. Closing.
