### ISSUE TITLE
Port Yard Bird Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#15]
Yard Bird Suite has events listed on this webpage: https://yardbirdsuite.com/events/

Please name this artifact : yardbirdsuite-com

Link to Huginn  https://huginn-staging.herokuapp.com/scenarios/59/diagram

@dev-aravind Please use the existing repo artsdata-orion to add your code and workflows. This will be a repo for many websites which we can do together in the same repo because no one else is collaborating on these. I think we will hit 100 websites before the end of the year, so please consider the structure of the code to not repeat (DRY). If in the future, an organization wants we can split a website off into its own repo, but until then lets make them all in this repo if the repo does not already exist.

**Comment by dev-aravind** [comment]
@saumier I wrote a SPARQL in reference to the one you used for scenesfrancophones to fix the blank nodes. But as we had some [places](https://artsdata-nebula-d1ec887e2637.herokuapp.com/query/show?title=Place%20entities%20in%20yardbirdsuite-com%20%284159%20triples%29&sparql=list_places&placeholder=http://kg.artsdata.ca/culture-creates/artsdata-orion/yardbirdsuite-com) too with blank node issues, I made some modifications to it. But the blank nodes are not getting replaced by UUIDs as of now. Can you help me work on this one?

[SPARQL file](https://github.com/culturecreates/artsdata-orion/blob/main/sparql/replace_blank_nodes.sparql)

**Comment by saumier** [comment]
@dev-aravind I took a look at the data, and I think we don't need to replace blank nodes of the places because they are all nested inside the events. I only need a way to access the top level entities. So please use the same SPARQL as you did in IPAA.

Also, it is not a good idea to use URIs like schema:Event to filter unless you are using inferencing. This is because an event may have a type schema:MusicEvent which is a sub-class of schema:Event.  When inferencing is used (turned on), then filtering with schema:Event will include all sub-classes. You can see that schema:MusicEvent is a  subClassOf schema:Event used in Artsdata here https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fschema.org%2FMusicEvent

**Comment by dev-aravind** [comment]
@saumier The blank node replacement is up in this [PR](https://github.com/culturecreates/artsdata-orion/pull/25) along with unit tests. Please review it and let me know if you need any changes.

**Comment by saumier** [comment]
@dev please check my requested changes in the https://github.com/culturecreates/artsdata-orion/pull/25.

**Comment by dev-aravind** [comment]
@saumier Other than the eventAttendanceMode and eventStatus vallues. The data looks fine. Let me know what you think

**Comment by saumier** [comment]
@dev-aravind Looking good. I have one question... Why is the description missing from this event even though it is present in the JSON-LD of the Web Page? It shows as "&nbsp;" in graphdb. https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=urn%3Auuid%3A55828532-6126-418a-9cd7-1e9e26895590

**Comment by dev-aravind** [comment]
@saumier The description for this event is a non-breaking space. 



![Image](https://github.com/culturecreates/artsdata-orion/assets/132546883/14d6e9ab-a947-4dd0-9a9e-a54145edf74d)

**Comment by dev-aravind** [comment]
@saumier Assigning this to you as the description was retained on re-running the workflow

**Comment by saumier** [comment]
Looks good.
