### ISSUE TITLE
Port Japanese Canadian Artists Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#16]
Japanese Canadian Artists - Load artists of all webpages lists here: https://japanesecanadianartists.com/artist/

Old Huginn - https://huginn-staging.herokuapp.com/scenarios/10

Please name this artifact: japanesecanadianartists-com

**Comment by dev-aravind** [comment]
@saumier I wrote a workflow for this website but couldn't find the data anywhere in nebula. Can you please check? This is the [JSON-LD File](https://raw.githubusercontent.com/culturecreates/artsdata-orion/main/output/japanesecanadianartists.jsonld)

**Comment by saumier** [comment]
@dev-aravind I took a look at the site and it looks like they removed their structured data.  The web pages only have the OpenGraph "http://ogp.me/ns#type" types of **article** which we don't yet focus on in Artsdata. If the OpenGraph data was complementary with some other types such as schema:type Person, then I would find it useful. For example, the OpenGraph often can give us a hint about the language of the webpage. So I would normally keep the ogp data as secondary info. But since there are no schema:Person or any other main "type" of structured data entities for Artsdata, let's remove this website completely.

**Comment by dev-aravind** [comment]
@saumier I've removed the Japanese Canadian artists workflow and JSON-LD from orion.
