### ISSUE TITLE
Add aramusique.org and saskatoonsymphony.org JSON-LD

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#36]
Tammy has requested that we add these 2 websites to Artsdata using the artsdata-orion repo.

Aramusique | https://www.aramusique.org/evenements/

Saskatoon Symphony Orchestra | https://saskatoonsymphony.org/season/

**Comment by dev-aravind** [comment]
@saumier The data for both of these websites are up in Nebula now. Please review them and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind 

- [ ] Aramusique.org looks good. 

saskatoonsymphony.org needs some changes. 

The idea of using `urn:` is something I would like to steer away from because we lose the domain name. The domain name in the URI gives a strong sense of authority. I tried this out in IPAA. Please update the blank node replacement SPARQL in Orion with a generic way to generate URIs with `domain name + UUID`.

I made the change for IPAA here for comparison
https://github.com/culturecreates/artsdata-orion/blob/main/sparql/replace_blank_nodes.sparql

**Comment by dev-aravind** [comment]
@saumier I fixed the issue with the URI. Please review it and let me know if you need any changes.
