### ISSUE TITLE
2425-W-001 Feasibility Study of iCal Standards

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#38]
# Work:
Assess feasibility and desirability of encoding Artsdata event data into different iCal standards (RFC 5545 to RFC 9253).
Prepare a report including include:
Mapping of Artsdata required and recommended event properties to iCal standards (including one column for each standard, as necessary/if relevant);
Sample JSON-LD and iCal encoding of a given event;
Qualitative assessment of how much critical information and content would be lost in the different iCal standards.
This project can be led primarily in Github. If spreadsheets and Google Docs are created, they should be stored in [Artsdata/Specifications/Artsdata to iCal](https://drive.google.com/drive/folders/1SG4BmIVMYfcYA1OVEBWH-cuCe-mQOYlB?usp=sharing).

# Objective:
Based on the outcomes of this first iteration, we should be able to determine:
A) It makes sense, and we should quote work for developing a method of providing iCal data outputs; or,
B) It has potential, but we should further investigate which iCal standards are supported by the main WordPress and Drupal events calendar before moving forward with development.

# Timeline:
The Artsdata community group and staff will be revising a three-year action plan for Artsdata over the spring. It would be useful to have the deliverable by mid-May, if possible.

**Comment by saumier** [comment]
@sahalali Let me know if you'd like to take on this feasibility study or propose a team member. It is only documentation, and not the actual implementation. This is a "work order" from our CAPACOA client. I think it will be a very interesting additional to Artsdata, as well as something we could decide to add to Footlight CMS after.

**Comment by dev-aravind** [comment]
@saumier The first draft of the document can be found [here](https://docs.google.com/document/d/1QQlFJVHkSccP1zlN5_50y4LwE-lz8I8oWxyCXYgvaxM/edit)

**Comment by saumier** [comment]
@dev-aravind I added some comments in the document. Please review. Thx.

**Comment by dev-aravind** [comment]
@saumier I updated the doc and also responded to your comments. Can you review them? Thanks.

**Comment by dev-aravind** [comment]
@saumier I updated the document conclusion, added timezone details into the sample iCal file and also replied to some of your comments. I think that we should proceed with RFC 5545 as it is the more widely used standard and will have more third party support and longevity. The other standards(jCal and xCal ) don't make sense to me as they are not used nearly as much as iCal and require more effort to work on. What do you think?

**Comment by saumier** [comment]
@dev-aravind I started to review the doc and added the missing links to the RFCs. This led me to see that there are several updates to the RFC 5545. I think about 10 related updates. These are significant because they can introduce properties that we could use. Please create a table with the properties added by each spec that updates 5545 and indicate if they are applicable to our case. I am at an external meeting all day but let me know if you can do this by tomorrow's standup as this document is past the deliverable date.

**Comment by saumier** [comment]
@dev-aravind I have made many changes and have now sent the document to CAPACOA for their review as the deadline had passed.  If you comment in the document they will be seen by Frederic at CAPACAO. You are still welcome to comment but I think we should move on to our other dev tasks. Thanks for working on this. Since I re-wrote a lot of it I added by name as author along with yours. So you could say we co-authored this ;-).

**Comment by saumier** [comment]
@tammy-culture This WO is closed. You can send final invoice if not already done. Thx.
