### ISSUE TITLE
Estimate WO-006 ICAL Output

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#48]
Please estimate work. Write down your assumptions and breakdown the project in a couple of tasks with hr estimates.

Work Order Doc for Gregory to fill out: https://docs.google.com/document/d/1hQ7l2VsBc5uuk_n_bTyiavMe2mU-bSCOuXxU6GCSLhU/edit

**Comment by dev-aravind** [comment]
@saumier 

Rough estimate:

Create a initialize NestJS application - 1h 
Create an API to call the Artsdata API - 2h
Add option to add custom SPARQL (Optional) - 4h
Modify the API to generate an ics file using a [library](https://www.npmjs.com/package/ical-generator) - 8h
Return the ics file - 2h
Testing - 3h

Total - 20h
