### ISSUE TITLE
Please grab JSON-LD from the Imperial Theatre website and add it to Artsdata.ca.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/artsdata-orion#59]
Please grab JSON-LD from the following website (https://imperialtheatre.ca/) and add it to Artsdata.ca.

It is request from ArtscultureNB for Footlight CMS.

Thank you.

**Comment by saumier** [comment]
@dev-aravind Please add this website to Orion.

**Comment by dev-aravind** [comment]
@saumier The data is now available in Artsdata, under the dataset - imperialtheatre-ca. The event type in the JSON-LD is http://schema.org/TheaterEvent, so it is not showing up in Artsdata as of now. Please review this and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind  One adjustment needed. Please create a new sparql to transform the PostalAddress object so that the schema:addressCountry is a string and not an object.  This would be a new sparql with a new tests and applied to all websites (so part of the main standard script).

**Comment by dev-aravind** [comment]
@saumier I added the SPARQL and also updated the data. Please let me know if you need any more changes.
