### ISSUE TITLE
Add kingstongrand.ca JSON-LD to Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#60]
https://www.kingstongrand.ca/events has very good JSON-LD.

Please create a new artifact `kingstongrand-ca` in Orion.

**Comment by dev-aravind** [comment]
@saumier The data is now crawled and available [here](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20kingstongrand-ca&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-orion/kingstongrand-ca).

**Comment by saumier** [comment]
@dev-aravind  Great.  Looks good. How can we improve the process? Do you think it is a good time to create an Action to create a reusable process?
