### ISSUE TITLE
Reusable workflow fetch-and-push-to-artsdata.yml

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#66]
I would like to have a reusable workflow that includes all the user inputs including headless-browser.

Please update the fetch-and-push-to-artsdata.yml and add what is missing, then refactor all the workflows to use it.

**Comment by saumier** [comment]
Looking really good. A few things I noticed:

- [ ] rcaaq-events.yml seems to have extra code - remove fetch-and-commit-data?
- [ ] indent for on: has extra tab - remove one tab
- [ ] rename fetch-and-push-to-artsdata.yml to fetch-data.yml because it only fetches data (I like this because it enables flexibility to add intermediate steps)


Also, can you make an **additional** workflow that combines the fetch and push parts so when there are no intermediate steps (like in replace-location-name) then it can all be a single workflow?  

- [ ] additional workflow fetch-and-push-to-artsdata.yml (same name but with additional included push)

**Comment by dev-aravind** [comment]
@saumier The workflow is now added. Let me know if you want to update all the crawl workflow to use this.

**Comment by saumier** [comment]
@dev-aravind I am thinking that the fetch-and-push-to-artsdata.yml should reuse the fetch-data.yml so it does not repeat.  We will be keeping both the fetch-data.yml and the fetch-and-push-to-artsdasta.yml. If you agree then please update.

**Comment by dev-aravind** [comment]
@saumier All the workflows now use the reusable workflow to fetch and push the data.

**Comment by saumier** [comment]
Looks good.
