### ISSUE TITLE
Add Agora de la Danse

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#67]
Good JSON-LD

https://agoradanse.com/evenement/montreal-marrakech/?utm_source=fb&utm_medium=Facebook_Mobile_Feed&utm_campaign=120211877123720753&fbclid=IwZXh0bgNhZW0BMAABHToAQwEUL2gvJgRPRTTbIXvTlaiA3akDqBK4DcG97r2jWKYI1n0LQdUHEw_aem_F-kVG3LEqMQx8UnatShSEQ

**Comment by dev-aravind** [comment]
@saumier This source is now available in artsdata [here](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20agoradanse-com&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-orion/agoradanse-com).

**Comment by saumier** [comment]
@dev-aravind  Excellent. Closing.

**Comment by saumier** [comment]
@dev-aravind I noticed that the listing page is not right. It should be https://agoradanse.com/evenement/. Please update the workflow.  

BTW the link I gave in the description of this issue was a link to one event to illustrate the quality of the JSON-LD, and not the listing page of the events on the website.  Sorry about that.

**Comment by dev-aravind** [comment]
@saumier I updated the workflow to fetch the correct URL. Please test [this](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20agoradanse-com&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-orion/agoradanse-com) and let me know if you need any changes.
