### ISSUE TITLE
Analyze LaVitrine site for crawling

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#68]
Analyze the website lavitrine.com to see if we can crawl their events using our current code in Orion, or if there is development needed in our current ruby/workflows. You can try loading it to see.  If there is development needed, please describe it and give a rough work estimate.

Change requested: Use the workflow artifacts to save the dump after fetching the data instead of committing to the repo. The artifact should be set to last for 8 days before being automatically removed. If this approach is successful then we can replace it everywhere instead of committing the file to the repo, and add a parameter to set the duration for keeping the artifact in Github with a default of 8 days ( 1 week plus 1 day).

Here is a complete event listing [link](https://www.lavitrine.com/en/search?query=%7B%22facets%22%3A%5B%5D%2C%22query%22%3A%22%22%2C%22page%22%3A0%2C%22modal%22%3A%22events_search%22%2C%22sorting%22%3A%22%22%2C%22dateFilters%22%3A%5B%5D%2C%22options%22%3A%7B%22hitsPerPage%22%3A%7B%22default%22%3A20%2C%22events_search%22%3A20%2C%22exhibitions_search%22%3A0%2C%22eventseries_search%22%3A0%2C%22places_full%22%3A0%2C%22artists%22%3A0%7D%2C%22aroundRadius%22%3A%7B%22default%22%3A30000%2C%22events_search%22%3A30000%2C%22exhibitions_search%22%3A30000%2C%22eventseries_search%22%3A30000%2C%22places_full%22%3A30000%2C%22artists%22%3Anull%7D%2C%22aroundLatLng%22%3A%7B%22events_search%22%3Anull%2C%22exhibitions_search%22%3Anull%2C%22eventseries_search%22%3Anull%2C%22places_full%22%3Anull%2C%22artists%22%3Anull%7D%2C%22page%22%3A%7B%22default%22%3A0%2C%22events_search%22%3A0%2C%22exhibitions_search%22%3A0%2C%22eventseries_search%22%3A0%2C%22places_full%22%3A0%2C%22artists%22%3A0%7D%2C%22paginationLimitedTo%22%3A%7B%22events_search%22%3Anull%2C%22exhibitions_search%22%3Anull%2C%22eventseries_search%22%3Anull%2C%22places_full%22%3Anull%2C%22artists%22%3Anull%7D%2C%22numericFilters%22%3A%5B%5D%7D%7D)

This is a large site with about 7000 events. Also, there are different sections for Events, Exhibitions, Festivals and series.

We also want to crawl Artists and Organizations, and Places.

Specifically, is there any ruby or workflow development needed to get the JSON-LD into Artsdata without worrying about the quality of the JSON-LD (ok to ignore SHACL violations).

Can we:
- [ ] crawl first page of events (headless or normal)
- [ ] crawl all events (does pagination work with this site?)
- [ ] crawl festivals 
- [ ] crawl exhibitions
- [ ] crawl Artists and Organizations
- [ ] crawl Places

**Comment by dev-aravind** [comment]
@saumier 

Rough estimate for changes needed:

Write a script to get all the ShadowRoot information from the website for the listing page - 3h
Update orion to support getting entity URLs using the ShadowRoot method. - 3h
Crawling the data - 2h
Testing -1h

Total - 9h

**Comment by saumier** [comment]
@dev-aravind Did you include in your estimate the change requested: Use workflow artifacts to save the dump?

**Comment by dev-aravind** [comment]
@saumier The estimate is now updated.
