### ISSUE TITLE
Remove type schema:SiteNavigationElement and others

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#69]
When crawling JSON-LD from websites with Orion, there are many objects that get included and stored in Artsdata.  Many of these objects are not needed. 

For all sites cralwed with Orion, please remove objects of [type](http://www.w3.org/1999/02/22-rdf-syntax-ns#type) schema:SiteNavigationElement

Other similar requests may follow after this task is completed.

Test case:
This url from imperialtheatre.ca has many SiteNavigationElement objects that should disappear.
https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fimperialtheatre.ca%2Fevent%2Fretro-film-national-lampoons-vacation-1983%2F

**Comment by dev-aravind** [comment]
@saumier I added a SPARQL to remove the type that you mentioned [here](https://github.com/culturecreates/artsdata-orion/blob/main/sparql/remove_objects.sparql). But it not working properly as of now as it leaves behind the type triple. Can you look into this?

**Comment by dev-aravind** [comment]
Task for dev: Add a unit test to check the SPARQL.

**Comment by saumier** [comment]
@dev-aravind Please also remove http://schema.org/WPHeader and  http://schema.org/WPFooter

**Comment by dev-aravind** [comment]
@saumier I updated the SPARQL and the unit tests to remove the above mentioned fields. Please review this and let me know if you need any more changes.
