### ISSUE TITLE
User Agent for scraping JSON-LD

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#73]
Some websites detect the User Agent of crawlers to grant permissions for scrapping JSON-LD. One such website is a ticketing platform called Ticketpro. Our CAPACOA client would like us to crawl the JSON-LD on their site. CAPACOA needs to inform Ticketpro so they allow the User Agent to read their JSON-LD.

Please find out:
- [x] what is the User Agent currently used in the Orion code (RDF.rb)
- [x] Can we set it to something else like "Artsdata.ca Crawler"

**Comment by saumier** [comment]
@dev-aravind This may require looking into the RDF.rb Gem. I can help if you get blocked.

**Comment by dev-aravind** [comment]
@saumier The default user-agent is of the format "Ruby RDF.rb/#{RDF::VERSION}", for example "user-agent" = ["Ruby RDF.rb/3.3.1"]. This can be manually modified, please confirm what do you want it to be. Thanks. 

source - https://github.com/ruby-rdf/rdf/blob/884e3ef780848e6254ab33e5550e82c2a16cfa4b/lib/rdf/util/file.rb#L47

**Comment by dev-aravind** [comment]
Note for @dev-aravind : The user-agent should be artsdata-crawler/{version}, for example artsdata-crawler/3.3.1.

**Comment by dev-aravind** [comment]
@saumier The user-agent is now updated.

**Comment by saumier** [comment]
@dev-aravind Will this also be the version for crawling using the headless option?

**Comment by dev-aravind** [comment]
@saumier will check with ticket-pro website and confirm whether the orion crawl is working in both headless and headful mode.

**Comment by fjjulien** [comment]
Ticketpro indicated via email yesterday that they added the Artsdata crawler to their list of authorized crawlers.
