### ISSUE TITLE
Analyze Ticketpro ETL and estimate work

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#76]
Please analyze and estimate the work to ETL Event data from Ticketpro, a ticketing platform. 
https://www.ticketpro.ca

We are interested in all their events including those in: Quebec, Atlantic region, and Ontario and western Canada. Each region may be a different artifact if needed.

Ticketpro authorized Artsdata's crawler to read their structured data.

You may try to use the new Action or if that is not sufficient, you may analyse and attempt other approaches, to complete a first ETL.  If none of our current approaches work then please describe what will need to be built in order to ETL this new ticketing platform.

**Comment by dev-aravind** [comment]
@saumier 

Rough estimate:

Update the workflow to fix the entity URLs issue (https://ww1.ticketpro.ca/event.php?event_id=6819 is sometimes fetched as https://ww1.ticketpro.caevent.php?event_id=6819) - 0.5 hr

Add a new workflow to fetch events - 2h

Testing and verification - 1.5 hr

Total - 4h
