### ISSUE TITLE
2425-W-005 Final Report

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#89]
A final report based on the following text from the WO:

> ## Specific crawling instructions
> This website has a complex layout that required custom crawlers to list and load all of the relevant pages that Skip recommends we crawl:
>*  Create a dedicated repo for tracking issues and collaboration with OSAC called artsdata-planet-osac
> * assign URIs using event blank nodes (domain + UUID)
> * include prov:wasDerivedFrom "url scraped" to all entities on the webpage scrapped
> * Check time-zones:I think time zones are fine, so no need to touch them but double check
> * Provide some comments on the quality of their JSON-LD including violations marked in Artsdata
> ### Pages to crawl as recommended by OSAC
> #### For Performing arts:
> Visit page https://www.osac.ca/performing-arts/performances?run=patours to get the list of tours
> For each tour visit the tour page. Example: https://www.osac.ca/index.php?option=com_content&view=article&id=156&Itemid=1821&artist=Becoming%2Bthe%2BBeatles
> https://www.osac.ca/index.php?option=com_content&view=article&id=156&Itemid=1821&artist=Becoming%2Bthe%2BBeatles
> For each date visit the link to capture the event JSON-LD. Example:
> https://www.osac.ca/performing-arts/event/121-PA8812/becoming-the-beatles-dekker-centre
> #### For Exhibitions:
> Visit page https://www.osac.ca/visual-media-arts/exhibitionsvma?run=exhibitions to get the list of exhibitions
> For each exhibition visit the exhibition page. Example: https://www.osac.ca/index.php?option=com_content&view=article&id=157&artist=A+Selection+of+Specimens&Itemid=1822
> For each date visit the link to capture the event JSON-LD. Example:
> https://osac.ca/visual-media-arts/event/112-VA4088/a-selection-of-specimens-last-mountain-lake-cultural-centre&Itemid=1819
> ### Past events are optional
> Dates for current and upcoming events are listed first and past event are listed at the end.
> We need only crawl upcoming events. But it is OK to crawl past events if it is more work to remove them.
> This VA Page has Exhibitions and Past Exhibitions:
> https://www.osac.ca/index.php?option=com_content&view=article&id=157&artist=All+Conditioned+Things%3A+Jared+Boechler+and+Nic+Wilson&Itemid=1822
> None of the Performing Arts pages have Past Performances yet as our season has not started, but once the dates are past those performances move to a Past Performances list below the current list.

**Comment by saumier** [comment]
@dev-aravind Can you please work on the final report for this WO. Please spend only a hour and add your notes on issues you had when working on it.  I will review our doc and add my own comments.  Thx.

**Comment by dev-aravind** [comment]
@saumier You can find the report [here](https://docs.google.com/document/d/1iomyyPxPJLecy93k4bfaOPDUwzV-LoBrMq7VT0dYuO0/edit?tab=t.0).

**Comment by saumier** [comment]
@dev-aravind Thanks for your report. I added my parts and sent to our client Frederic at CAPACOA for review.
https://docs.google.com/document/d/15pcxmLO5x3QSnxjGpxZ1_-qFdAvPK4p2u2-XclOu99I/edit?tab=t.0#heading=h.l05c128a4z2h
