### ISSUE TITLE
Semantic version of Artsdata Pipeline Action

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#93]
As a dev user of the Artsdata Pipeline Action, I don't want to have to update my workflow.yml every time there is a patch in the Artsdata Pipeline Action. For example, I should be able to use `@2` or `@2.0 `instead of `@2.0.3`.

**Comment by dev-aravind** [comment]
@saumier You can use a floating tag that points to latest release here. I updated the deploy workflow to include that.
