### ISSUE TITLE
capitol-nb-ca workflow failing

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#94]
The workflow for capitol-nb-ca is failing after being updated. The website has improved their JSON-LD. Gregory removed the custom location from the workflow and set the mode "fetch-push".

https://github.com/culturecreates/artsdata-orion/actions/workflows/capitolnb-events.yml

**Comment by dev-aravind** [comment]
@saumier This is happening because the [october events](https://capitol.nb.ca/en/tickets-events?filter_45=2024-10&cc=p) are now missing in the Capitol.nb website and the Artsdata Pipeline is configured to stop looking for event URLs when it doesn't find any new ones in a page.

This can be solved in 2 ways:

1. We just crawl the [first page](https://capitol.nb.ca/en/tickets-events).
2. We can use their pagination strategy, but it leads to redundant requests to their website. The website’s pagination displays 12 events per page, and the page numbers reflect this. The first page shows events 0–11, and the next page starts at event 12, effectively skipping any intermediate pages. This means that calling pages in a sequential order (1, 2, 3, ...) does not work as expected; only certain pages (0, 12, 24, etc.) will display unique sets of events. This method will fetch all events in their website.

Let me know what you think.

**Comment by saumier** [comment]
I think crawling the first page was ok in the beginning when we wanted to load data and see what it contained. But now we need a better solution that gets all their pages of events.

Please consider adding a parameter like "offset" to increment the pagination by more than one. In this case the offset would be 12 and the API calls would be https://capitol.nb.ca/en/tickets-events?start=1 followed by https://capitol.nb.ca/en/tickets-events?start=12 and then https://capitol.nb.ca/en/tickets-events?start=24

**Comment by dev-aravind** [comment]
@saumier I added a new parameter to include an offset to the pagination, but their JSON-LD seems to be having errors and are not being crawled as of now.

This is the error: /usr/share/rvm/gems/ruby-3.1.2/gems/json-ld-3.3.2/lib/json/ld/api.rb:718:in `rescue in loadRemoteDocument': loading document failed: 859: unexpected token at '{ (JSON::LD::JsonLdError::LoadingDocumentFailed)

What do you suggest?

**Comment by saumier** [comment]
@dev-aravind Looks like the code is having trouble parsing the JSON-LD. I will open a bug and try to fix it for you.

**Comment by saumier** [comment]
@dev-aravind The problem I found was a line feed (\n) inside the description string.  This was causing a JSON.parse error because the string was not a valid JSON.  It was happening in many of the event descriptions. 

I fixed it with some tests. The capitol-nb-ca has the JSON-LD in the html so it does not need the headless browser scrapping. I ran it set to "false" in the workflow and it collected 52 events. I then ran the workflow again with the headless option true and it collected

**Comment by saumier** [comment]
@dev-aravind I understand why the default parameter was not working.

I wrote the method `create_browser(headers: nil)` to default to nil.  This syntax should be called like this ` create_browser(headers: "Chrome")` or with no parameter `create_browser()`.

But instead the calling method uses a positional parameter like` create_browser("Chrome")`.   This means that I should have written the method create_browser(headers = nil).

Sorry about that. I was stuck not being able to test the larger system.

**Comment by saumier** [comment]
@dev-aravind I have made quite a few changes but I am still working on it. I'll need a some more time before I hand it back over to you.

**Comment by saumier** [comment]
@dev-aravind Please review.  I made more changes to the code because I was having trouble with inconsistent results when running the full pipeline that I could not reproduce with the unit tests.  I started using classes and instantiating instances. But in the end this was not the problem. The problem was related to the way the blank nodes where being processed. The fix in the end was to add `options = {unique_bnodes: true}`.  Please test and create a build so we can try in out by loading capitol-nb-ca into Artsdata.

**Comment by dev-aravind** [comment]
@saumier Please review [this](https://github.com/culturecreates/artsdata-pipeline-action/pull/9) pull request.

**Comment by saumier** [comment]
@dev-aravind I reviewed the PR and merged into main. Please publish a new version so we can test with the Orion sites.

**Comment by dev-aravind** [comment]
@saumier We are now receiving 60+ events from the crawl process. You can find them [here](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20capitol-nb-ca&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-orion/capitol-nb-ca).
